// <auto-generated />
using HealthWellbeing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthWellbeing.Migrations
{
    [DbContext(typeof(HealthWellbeingDbContext))]
    [Migration("20251110111723_2")]
    partial class _2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComponenteReceitaReceita", b =>
                {
                    b.Property<int>("ComponentesComponenteReceitaId")
                        .HasColumnType("int");

                    b.Property<int>("ReceitaRelacionadasReceitaId")
                        .HasColumnType("int");

                    b.HasKey("ComponentesComponenteReceitaId", "ReceitaRelacionadasReceitaId");

                    b.HasIndex("ReceitaRelacionadasReceitaId");

                    b.ToTable("ComponenteReceitaReceita");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergia", b =>
                {
                    b.Property<int>("AlergiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlergiaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gravidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AlergiaId");

                    b.ToTable("Alergia");
                });

            modelBuilder.Entity("HealthWellbeing.Models.AlergiaAlimento", b =>
                {
                    b.Property<int>("AlergiaId")
                        .HasColumnType("int");

                    b.Property<int>("AlimentoId")
                        .HasColumnType("int");

                    b.HasKey("AlergiaId", "AlimentoId");

                    b.HasIndex("AlimentoId");

                    b.ToTable("AlergiaAlimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alimento", b =>
                {
                    b.Property<int>("AlimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlimentoId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaAlimentoId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GorduraGPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HidratosGPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KcalPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProteinaGPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AlimentoId");

                    b.HasIndex("CategoriaAlimentoId");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.AlimentoSubstituto", b =>
                {
                    b.Property<int>("AlimentoSubstitutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlimentoSubstitutoId"));

                    b.Property<int>("AlimentoOriginalId")
                        .HasColumnType("int");

                    b.Property<int>("AlimentoSubstitutoRefId")
                        .HasColumnType("int");

                    b.Property<double?>("FatorSimilaridade")
                        .HasColumnType("float");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProporcaoEquivalente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RestricaoAlimentarId")
                        .HasColumnType("int");

                    b.HasKey("AlimentoSubstitutoId");

                    b.HasIndex("AlimentoOriginalId");

                    b.HasIndex("AlimentoSubstitutoRefId");

                    b.HasIndex("RestricaoAlimentarId");

                    b.ToTable("AlimentoSubstitutos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.CategoriaAlimento", b =>
                {
                    b.Property<int>("CategoriaAlimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaAlimentoId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaAlimentoId");

                    b.ToTable("CategoriaAlimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ComponenteReceita", b =>
                {
                    b.Property<int>("ComponenteReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComponenteReceitaId"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpcional")
                        .HasColumnType("bit");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeMedida")
                        .HasColumnType("int");

                    b.HasKey("ComponenteReceitaId");

                    b.HasIndex("AlimentoId");

                    b.ToTable("ComponenteReceita");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Receita", b =>
                {
                    b.Property<int>("ReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceitaId"));

                    b.Property<decimal>("Calorias")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("ComponentesReceitaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Gorduras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HidratosCarbono")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Porcoes")
                        .HasColumnType("int");

                    b.Property<decimal>("Proteinas")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("RestricoesAlimentarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempoPreparo")
                        .HasColumnType("int");

                    b.HasKey("ReceitaId");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("HealthWellbeing.Models.RestricaoAlimentar", b =>
                {
                    b.Property<int>("RestricaoAlimentarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestricaoAlimentarId"));

                    b.Property<int?>("AlimentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Gravidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("RestricaoAlimentarId");

                    b.HasIndex("AlimentoId");

                    b.ToTable("RestricaoAlimentar");
                });

            modelBuilder.Entity("ReceitaRestricaoAlimentar", b =>
                {
                    b.Property<int>("ReceitasReceitaId")
                        .HasColumnType("int");

                    b.Property<int>("RestricoesAlimentaresRestricaoAlimentarId")
                        .HasColumnType("int");

                    b.HasKey("ReceitasReceitaId", "RestricoesAlimentaresRestricaoAlimentarId");

                    b.HasIndex("RestricoesAlimentaresRestricaoAlimentarId");

                    b.ToTable("ReceitaRestricaoAlimentar");
                });

            modelBuilder.Entity("ComponenteReceitaReceita", b =>
                {
                    b.HasOne("HealthWellbeing.Models.ComponenteReceita", null)
                        .WithMany()
                        .HasForeignKey("ComponentesComponenteReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Receita", null)
                        .WithMany()
                        .HasForeignKey("ReceitaRelacionadasReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthWellbeing.Models.AlergiaAlimento", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alergia", "Alergia")
                        .WithMany("AlimentosAssociados")
                        .HasForeignKey("AlergiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Alimento", "Alimento")
                        .WithMany("AlergiaRelacionadas")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alergia");

                    b.Navigation("Alimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alimento", b =>
                {
                    b.HasOne("HealthWellbeing.Models.CategoriaAlimento", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaAlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("HealthWellbeing.Models.AlimentoSubstituto", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alimento", "AlimentoOriginal")
                        .WithMany("Substitutos")
                        .HasForeignKey("AlimentoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Alimento", "AlimentoSubstitutoRef")
                        .WithMany("SubstituidoPor")
                        .HasForeignKey("AlimentoSubstitutoRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.RestricaoAlimentar", null)
                        .WithMany("Substitutos")
                        .HasForeignKey("RestricaoAlimentarId");

                    b.Navigation("AlimentoOriginal");

                    b.Navigation("AlimentoSubstitutoRef");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ComponenteReceita", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alimento", "Alimento")
                        .WithMany()
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.RestricaoAlimentar", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alimento", "Alimento")
                        .WithMany()
                        .HasForeignKey("AlimentoId");

                    b.Navigation("Alimento");
                });

            modelBuilder.Entity("ReceitaRestricaoAlimentar", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Receita", null)
                        .WithMany()
                        .HasForeignKey("ReceitasReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.RestricaoAlimentar", null)
                        .WithMany()
                        .HasForeignKey("RestricoesAlimentaresRestricaoAlimentarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergia", b =>
                {
                    b.Navigation("AlimentosAssociados");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alimento", b =>
                {
                    b.Navigation("AlergiaRelacionadas");

                    b.Navigation("SubstituidoPor");

                    b.Navigation("Substitutos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.RestricaoAlimentar", b =>
                {
                    b.Navigation("Substitutos");
                });
#pragma warning restore 612, 618
        }
    }
}
