// <auto-generated />
using System;
using HealthWellbeing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthWellbeing.Migrations
{
    [DbContext(typeof(HealthWellbeingDbContext))]
    [Migration("20251124191832_WhitFoodInTake")]
    partial class WhitFoodInTake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthWellbeing.Models.Alergia", b =>
                {
                    b.Property<int>("AlergiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlergiaID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("Gravidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AlergiaID");

                    b.HasIndex("FoodId");

                    b.ToTable("Alergia");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergy", b =>
                {
                    b.Property<int>("AlergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlergyId"));

                    b.Property<string>("AlergyName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("AlergyId");

                    b.ToTable("Alergy");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("CreateMember")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ClientAlergy", b =>
                {
                    b.Property<int>("ClientAlergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientAlergyId"));

                    b.Property<int>("AlergyId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("ClientAlergyId");

                    b.HasIndex("AlergyId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientAlergy");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodInTakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FoodId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FoodInTakeId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("FoodCategory");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodInTake", b =>
                {
                    b.Property<int>("FoodInTakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodInTakeId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eaten")
                        .HasColumnType("bit");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("FoodInTakeId");

                    b.ToTable("FoodInTake");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodNutritionalComponent", b =>
                {
                    b.Property<int>("FoodNutritionalComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodNutritionalComponentId"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("NutritionalComponentId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("FoodNutritionalComponentId");

                    b.HasIndex("FoodId");

                    b.HasIndex("NutritionalComponentId");

                    b.ToTable("FoodNutritionalComponent");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodPlan", b =>
                {
                    b.Property<int>("PlanFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanFoodId"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("PortionId")
                        .HasColumnType("int");

                    b.HasKey("PlanFoodId");

                    b.HasIndex("FoodId");

                    b.HasIndex("PlanId");

                    b.HasIndex("PortionId");

                    b.ToTable("FoodPlan");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("int");

                    b.Property<int>("DailyFat")
                        .HasColumnType("int");

                    b.Property<int>("DailyFibers")
                        .HasColumnType("int");

                    b.Property<int>("DailyHydrates")
                        .HasColumnType("int");

                    b.Property<int>("DailyMinerals")
                        .HasColumnType("int");

                    b.Property<int>("DailyProtein")
                        .HasColumnType("int");

                    b.Property<int>("DailyVitamins")
                        .HasColumnType("int");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GoalId");

                    b.HasIndex("ClientId");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Member", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("HealthWellbeing.Models.NutritionalComponent", b =>
                {
                    b.Property<int>("NutritionalComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionalComponentId"));

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NutritionalComponentId");

                    b.ToTable("NutritionalComponent");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Nutritionist", b =>
                {
                    b.Property<int>("NutritionistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionistId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("NutritionistId");

                    b.ToTable("Nutritionist");
                });

            modelBuilder.Entity("HealthWellbeing.Models.NutritionistClientPlan", b =>
                {
                    b.Property<int>("PlanClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanClientId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("NutritionistId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("PlanClientId");

                    b.HasIndex("ClientId");

                    b.HasIndex("NutritionistId");

                    b.HasIndex("PlanId");

                    b.ToTable("NutritionistClientPlan");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FoodInTakeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PlanId");

                    b.HasIndex("FoodInTakeId");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Portion", b =>
                {
                    b.Property<int>("PortionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortionId"));

                    b.Property<string>("PortionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortionId");

                    b.ToTable("Portion");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Receita", b =>
                {
                    b.Property<int>("ReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceitaId"));

                    b.Property<decimal>("CaloriasPorPorcao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Gorduras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HidratosCarbono")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsLactoseFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetariana")
                        .HasColumnType("bit");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Porcoes")
                        .HasColumnType("int");

                    b.Property<decimal>("Proteinas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TempoPreparo")
                        .HasColumnType("int");

                    b.HasKey("ReceitaId");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("HealthWellbeing.Models.RestricaoAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gravidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RestricaoAlimentar");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergia", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ClientAlergy", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alergy", "Alergy")
                        .WithMany("ClientAlergies")
                        .HasForeignKey("AlergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithMany("ClientAlergies")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alergy");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Food", b =>
                {
                    b.HasOne("HealthWellbeing.Models.FoodCategory", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.FoodInTake", null)
                        .WithMany("Foods")
                        .HasForeignKey("FoodInTakeId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodNutritionalComponent", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Food", "Food")
                        .WithMany("FoodNutritionalComponents")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.NutritionalComponent", "NutritionalComponent")
                        .WithMany("FoodNutritionalComponents")
                        .HasForeignKey("NutritionalComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("NutritionalComponent");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodPlan", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Food", "Food")
                        .WithMany("FoodPlans")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Plan", "Plan")
                        .WithMany("FoodPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Portion", "Portion")
                        .WithMany("FoodPlans")
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Plan");

                    b.Navigation("Portion");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Goal", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithMany("Goals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Member", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithOne("Membership")
                        .HasForeignKey("HealthWellbeing.Models.Member", "ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.NutritionistClientPlan", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithMany("NutritionistClientPlans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Nutritionist", "Nutritionist")
                        .WithMany("NutritionistClientPlans")
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Plan", "Plan")
                        .WithMany("NutritionistClientPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Nutritionist");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Plan", b =>
                {
                    b.HasOne("HealthWellbeing.Models.FoodInTake", null)
                        .WithMany("Plans")
                        .HasForeignKey("FoodInTakeId");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergy", b =>
                {
                    b.Navigation("ClientAlergies");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Client", b =>
                {
                    b.Navigation("ClientAlergies");

                    b.Navigation("Goals");

                    b.Navigation("Membership");

                    b.Navigation("NutritionistClientPlans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Food", b =>
                {
                    b.Navigation("FoodNutritionalComponents");

                    b.Navigation("FoodPlans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodInTake", b =>
                {
                    b.Navigation("Foods");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.NutritionalComponent", b =>
                {
                    b.Navigation("FoodNutritionalComponents");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Nutritionist", b =>
                {
                    b.Navigation("NutritionistClientPlans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Plan", b =>
                {
                    b.Navigation("FoodPlans");

                    b.Navigation("NutritionistClientPlans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Portion", b =>
                {
                    b.Navigation("FoodPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
