// <auto-generated />
using System;
using HealthWellbeing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthWellbeing.Migrations
{
    [DbContext(typeof(HealthWellbeingDbContext))]
    [Migration("20251120162244_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthWellBeing.Models.Especialidade", b =>
                {
                    b.Property<int>("EspecialidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadeId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EspecialidadeId");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            EspecialidadeId = 1,
                            Nome = "Hematologia"
                        },
                        new
                        {
                            EspecialidadeId = 2,
                            Nome = "Radiologia"
                        },
                        new
                        {
                            EspecialidadeId = 3,
                            Nome = "Cardiologia"
                        },
                        new
                        {
                            EspecialidadeId = 4,
                            Nome = "Imagiologia"
                        },
                        new
                        {
                            EspecialidadeId = 5,
                            Nome = "Reumatologia"
                        },
                        new
                        {
                            EspecialidadeId = 6,
                            Nome = "Urologia"
                        },
                        new
                        {
                            EspecialidadeId = 7,
                            Nome = "Gastroenterologia"
                        },
                        new
                        {
                            EspecialidadeId = 8,
                            Nome = "Ginecologia"
                        },
                        new
                        {
                            EspecialidadeId = 9,
                            Nome = "Pneumologia"
                        },
                        new
                        {
                            EspecialidadeId = 10,
                            Nome = "Endocrinologia"
                        },
                        new
                        {
                            EspecialidadeId = 11,
                            Nome = "Imunoalergologia"
                        },
                        new
                        {
                            EspecialidadeId = 12,
                            Nome = "Neurologia"
                        },
                        new
                        {
                            EspecialidadeId = 13,
                            Nome = "Oftalmologia"
                        },
                        new
                        {
                            EspecialidadeId = 14,
                            Nome = "Otorrinolaringologia"
                        },
                        new
                        {
                            EspecialidadeId = 15,
                            Nome = "Dermatologia"
                        },
                        new
                        {
                            EspecialidadeId = 16,
                            Nome = "Medicina Legal"
                        });
                });

            modelBuilder.Entity("HealthWellBeing.Models.Exame", b =>
                {
                    b.Property<int>("ExameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExameId"));

                    b.Property<DateTime>("DataHoraMarcacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("ExameTipoId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialEquipamentoAssociadoId")
                        .HasColumnType("int");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicoSolicitanteId")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProfissionalExecutanteId")
                        .HasColumnType("int");

                    b.Property<int?>("SalaDeExameId")
                        .HasColumnType("int");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("ExameId");

                    b.HasIndex("ExameTipoId");

                    b.HasIndex("MaterialEquipamentoAssociadoId");

                    b.HasIndex("MedicoSolicitanteId");

                    b.HasIndex("ProfissionalExecutanteId");

                    b.HasIndex("SalaDeExameId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Exames");
                });

            modelBuilder.Entity("HealthWellBeing.Models.Utente", b =>
                {
                    b.Property<int>("UtenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtenteId"));

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Morada")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeEmergencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumCC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroEmergencia")
                        .HasColumnType("int");

                    b.Property<int>("UtenteSNS")
                        .HasColumnType("int");

                    b.HasKey("UtenteId");

                    b.ToTable("Utentes");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ExameTipo", b =>
                {
                    b.Property<int>("ExameTipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExameTipoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExameTipoId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("ExameTipo");

                    b.HasData(
                        new
                        {
                            ExameTipoId = 1,
                            Descricao = "Exame laboratorial de rotina para avaliação hematológica.",
                            EspecialidadeId = 1,
                            Nome = "Análise de Sangue Completa"
                        },
                        new
                        {
                            ExameTipoId = 2,
                            Descricao = "Exame de imagem detalhado para estruturas internas.",
                            EspecialidadeId = 2,
                            Nome = "Ressonância Magnética"
                        },
                        new
                        {
                            ExameTipoId = 3,
                            Descricao = "Avaliação da atividade elétrica do coração.",
                            EspecialidadeId = 3,
                            Nome = "Eletrocardiograma (ECG)"
                        },
                        new
                        {
                            ExameTipoId = 4,
                            Descricao = "Processamento de imagens por computador para criar visões transversais do corpo.",
                            EspecialidadeId = 2,
                            Nome = "Tomografia Computorizada (TAC)"
                        },
                        new
                        {
                            ExameTipoId = 5,
                            Descricao = "Utiliza ondas sonoras de alta frequência para criar imagens dos órgãos internos.",
                            EspecialidadeId = 4,
                            Nome = "Ecografia Abdominal"
                        },
                        new
                        {
                            ExameTipoId = 6,
                            Descricao = "Monitorização cardíaca durante exercício físico controlado.",
                            EspecialidadeId = 3,
                            Nome = "Teste de Esforço Cardíaco"
                        },
                        new
                        {
                            ExameTipoId = 7,
                            Descricao = "Mede a densidade mineral óssea para diagnosticar osteoporose.",
                            EspecialidadeId = 5,
                            Nome = "Densitometria Óssea"
                        },
                        new
                        {
                            ExameTipoId = 8,
                            Descricao = "Análise laboratorial de amostra de urina.",
                            EspecialidadeId = 6,
                            Nome = "Exame de Urina Tipo II"
                        },
                        new
                        {
                            ExameTipoId = 9,
                            Descricao = "Exame endoscópico para visualização do intestino grosso.",
                            EspecialidadeId = 7,
                            Nome = "Colonoscopia"
                        },
                        new
                        {
                            ExameTipoId = 10,
                            Descricao = "Exame do esófago, estômago e duodeno.",
                            EspecialidadeId = 7,
                            Nome = "Endoscopia Digestiva Alta"
                        },
                        new
                        {
                            ExameTipoId = 11,
                            Descricao = "Rastreio e diagnóstico de cancro da mama.",
                            EspecialidadeId = 2,
                            Nome = "Mamografia Digital"
                        },
                        new
                        {
                            ExameTipoId = 12,
                            Descricao = "Avaliação dos órgãos pélvicos femininos ou masculinos.",
                            EspecialidadeId = 8,
                            Nome = "Ecografia Pélvica"
                        },
                        new
                        {
                            ExameTipoId = 13,
                            Descricao = "Avalia a capacidade pulmonar e o fluxo de ar.",
                            EspecialidadeId = 9,
                            Nome = "Prova de Função Respiratória"
                        },
                        new
                        {
                            ExameTipoId = 14,
                            Descricao = "Monitorização contínua da atividade elétrica do coração.",
                            EspecialidadeId = 3,
                            Nome = "Holter 24 Horas"
                        },
                        new
                        {
                            ExameTipoId = 15,
                            Descricao = "Medição dos níveis de hormonas tiroideias no sangue.",
                            EspecialidadeId = 10,
                            Nome = "Análise Hormonal (Tireoide)"
                        },
                        new
                        {
                            ExameTipoId = 16,
                            Descricao = "Testes cutâneos para identificação de alergénios específicos.",
                            EspecialidadeId = 11,
                            Nome = "Teste de Alergias"
                        },
                        new
                        {
                            ExameTipoId = 17,
                            Descricao = "Registo da atividade elétrica cerebral.",
                            EspecialidadeId = 12,
                            Nome = "Eletroencefalograma (EEG)"
                        },
                        new
                        {
                            ExameTipoId = 18,
                            Descricao = "Visualização detalhada dos vasos sanguíneos.",
                            EspecialidadeId = 2,
                            Nome = "Angiografia por TC"
                        },
                        new
                        {
                            ExameTipoId = 19,
                            Descricao = "Avaliação da acuidade visual e pressão intraocular.",
                            EspecialidadeId = 13,
                            Nome = "Exame Oftalmológico Completo"
                        },
                        new
                        {
                            ExameTipoId = 20,
                            Descricao = "Avaliação da capacidade auditiva.",
                            EspecialidadeId = 14,
                            Nome = "Audiograma"
                        },
                        new
                        {
                            ExameTipoId = 21,
                            Descricao = "Colheita de pequena amostra de tecido cutâneo.",
                            EspecialidadeId = 15,
                            Nome = "Biopsia de Pele"
                        },
                        new
                        {
                            ExameTipoId = 22,
                            Descricao = "Detecção e quantificação de substâncias químicas no organismo.",
                            EspecialidadeId = 16,
                            Nome = "Análise Toxicológica"
                        },
                        new
                        {
                            ExameTipoId = 23,
                            Descricao = "Identificação de bactérias que podem causar infeção urinária.",
                            EspecialidadeId = 6,
                            Nome = "Cultura de Urina"
                        });
                });

            modelBuilder.Entity("HealthWellbeing.Models.Funcao", b =>
                {
                    b.Property<int>("FuncaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncaoId"));

                    b.Property<string>("NomeFuncao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("FuncaoId");

                    b.ToTable("Funcoes");
                });

            modelBuilder.Entity("HealthWellbeing.Models.MaterialEquipamentoAssociado", b =>
                {
                    b.Property<int>("MaterialEquipamentoAssociadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialEquipamentoAssociadoId"));

                    b.Property<string>("EstadoComponente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeEquipamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("MaterialEquipamentoAssociadoId");

                    b.ToTable("MaterialEquipamentoAssociado");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Medicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ProfissionalExecutante", b =>
                {
                    b.Property<int>("ProfissionalExecutanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfissionalExecutanteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ProfissionalExecutanteId");

                    b.HasIndex("FuncaoId");

                    b.ToTable("ProfissionalExecutante");
                });

            modelBuilder.Entity("HealthWellbeing.Models.SalaDeExames", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaId"));

                    b.Property<string>("Laboratorio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoSala")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SalaId");

                    b.ToTable("SalaDeExame");
                });

            modelBuilder.Entity("HealthWellBeing.Models.Exame", b =>
                {
                    b.HasOne("HealthWellbeing.Models.ExameTipo", "ExameTipo")
                        .WithMany()
                        .HasForeignKey("ExameTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.MaterialEquipamentoAssociado", "MaterialEquipamentoAssociado")
                        .WithMany()
                        .HasForeignKey("MaterialEquipamentoAssociadoId");

                    b.HasOne("HealthWellbeing.Models.Medicos", "MedicoSolicitante")
                        .WithMany()
                        .HasForeignKey("MedicoSolicitanteId");

                    b.HasOne("HealthWellbeing.Models.ProfissionalExecutante", "ProfissionalExecutante")
                        .WithMany()
                        .HasForeignKey("ProfissionalExecutanteId");

                    b.HasOne("HealthWellbeing.Models.SalaDeExames", "SalaDeExame")
                        .WithMany()
                        .HasForeignKey("SalaDeExameId");

                    b.HasOne("HealthWellBeing.Models.Utente", "Utente")
                        .WithMany("Exames")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExameTipo");

                    b.Navigation("MaterialEquipamentoAssociado");

                    b.Navigation("MedicoSolicitante");

                    b.Navigation("ProfissionalExecutante");

                    b.Navigation("SalaDeExame");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ExameTipo", b =>
                {
                    b.HasOne("HealthWellBeing.Models.Especialidade", "Especialidade")
                        .WithMany("TiposExame")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ProfissionalExecutante", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Funcao", null)
                        .WithMany("ProfissionaisExecutantes")
                        .HasForeignKey("FuncaoId");
                });

            modelBuilder.Entity("HealthWellBeing.Models.Especialidade", b =>
                {
                    b.Navigation("TiposExame");
                });

            modelBuilder.Entity("HealthWellBeing.Models.Utente", b =>
                {
                    b.Navigation("Exames");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Funcao", b =>
                {
                    b.Navigation("ProfissionaisExecutantes");
                });
#pragma warning restore 612, 618
        }
    }
}
