// <auto-generated />
using System;
using HealthWellbeing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthWellbeing.Migrations
{
    [DbContext(typeof(HealthWellbeingDbContext))]
    [Migration("20260105181617_Update2")]
    partial class Update2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeneficioTipoExercicio", b =>
                {
                    b.Property<int>("BeneficiosBeneficioId")
                        .HasColumnType("int");

                    b.Property<int>("TipoExercicioId")
                        .HasColumnType("int");

                    b.HasKey("BeneficiosBeneficioId", "TipoExercicioId");

                    b.HasIndex("TipoExercicioId");

                    b.ToTable("BeneficioTipoExercicio");
                });

            modelBuilder.Entity("ExercicioGenero", b =>
                {
                    b.Property<int>("ExercicioId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.HasKey("ExercicioId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("ExercicioGenero");
                });

            modelBuilder.Entity("ExercicioGrupoMuscular", b =>
                {
                    b.Property<int>("ExercicioId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("int");

                    b.HasKey("ExercicioId", "GrupoMuscularId");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("ExercicioGrupoMuscular");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActivityReward")
                        .HasColumnType("int");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ActivityType", b =>
                {
                    b.Property<int>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityTypeId");

                    b.ToTable("ActivityType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergia", b =>
                {
                    b.Property<int>("AlergiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlergiaID"));

                    b.Property<int?>("AlimentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gravidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AlergiaID");

                    b.HasIndex("AlimentoId");

                    b.ToTable("Alergia");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alimento", b =>
                {
                    b.Property<int>("AlimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlimentoId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaAlimentoId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GorduraGPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HidratosGPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KcalPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProteinaGPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AlimentoId");

                    b.HasIndex("CategoriaAlimentoId");

                    b.ToTable("Alimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<string>("BadgeDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BadgeTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("BadgeId");

                    b.HasIndex("BadgeTypeId");

                    b.ToTable("Badge");
                });

            modelBuilder.Entity("HealthWellbeing.Models.BadgeRequirement", b =>
                {
                    b.Property<int>("BadgeRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeRequirementId"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<string>("BadgeRequirementName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RequirementDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("RequirementType")
                        .HasColumnType("int");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.HasKey("BadgeRequirementId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("EventTypeId");

                    b.ToTable("BadgeRequirement");
                });

            modelBuilder.Entity("HealthWellbeing.Models.BadgeType", b =>
                {
                    b.Property<int>("BadgeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeTypeId"));

                    b.Property<string>("BadgeTypeDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BadgeTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BadgeTypeId");

                    b.ToTable("BadgeType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Beneficio", b =>
                {
                    b.Property<int>("BeneficioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficioId"));

                    b.Property<string>("DescricaoBeneficio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeBeneficio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BeneficioId");

                    b.ToTable("Beneficio");
                });

            modelBuilder.Entity("HealthWellbeing.Models.CategoriaAlimento", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("CategoriaAlimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LevelId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("HealthWellbeing.Models.CustomerBadge", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAwarded")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("CustomerBadge");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EventPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MinLevel")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("EventTypeId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("HealthWellbeing.Models.EventActivity", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int?>("ActivityId1")
                        .HasColumnType("int");

                    b.HasKey("EventId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ActivityId1");

                    b.ToTable("EventActivity");
                });

            modelBuilder.Entity("HealthWellbeing.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"));

                    b.Property<string>("EventTypeDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("EventTypeMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ScoringStrategyId")
                        .HasColumnType("int");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Exercicio", b =>
                {
                    b.Property<int>("ExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExercicioId"));

                    b.Property<double>("CaloriasGastas")
                        .HasColumnType("float");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duracao")
                        .HasColumnType("float");

                    b.Property<string>("EquipamentoNecessario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExercicioNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instrucoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intencidade")
                        .HasColumnType("int");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("ExercicioId");

                    b.ToTable("Exercicio");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"));

                    b.Property<string>("NomeGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GeneroId");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("HealthWellbeing.Models.GrupoMuscular", b =>
                {
                    b.Property<int>("GrupoMuscularId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupoMuscularId"));

                    b.Property<string>("GrupoMuscularNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocalizacaoCorporal")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("GrupoMuscularId");

                    b.ToTable("GrupoMuscular");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<int>("LevelPointsLimit")
                        .HasColumnType("int");

                    b.HasKey("LevelId");

                    b.HasIndex("LevelCategoryId");

                    b.ToTable("Level");
                });

            modelBuilder.Entity("HealthWellbeing.Models.LevelCategory", b =>
                {
                    b.Property<int>("LevelCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelCategoryId");

                    b.ToTable("LevelCategory");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MemberId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Member");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Musculo", b =>
                {
                    b.Property<int>("MusculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusculoId"));

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Musculo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MusculoId");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("Musculo");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanId");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ProblemaSaude", b =>
                {
                    b.Property<int>("ProblemaSaudeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProblemaSaudeId"));

                    b.Property<int>("Gravidade")
                        .HasColumnType("int");

                    b.Property<string>("ProblemaCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProblemaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZonaAtingida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProblemaSaudeId");

                    b.ToTable("ProblemaSaude");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ProfissionalExecutante", b =>
                {
                    b.Property<int>("ProfissionalExecutanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfissionalExecutanteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfissionalExecutanteId");

                    b.ToTable("ProfissionalExecutante");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Receita", b =>
                {
                    b.Property<int>("ReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceitaId"));

                    b.Property<decimal>("CaloriasPorPorcao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Gorduras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HidratosCarbono")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsLactoseFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetariana")
                        .HasColumnType("bit");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Porcoes")
                        .HasColumnType("int");

                    b.Property<decimal>("Proteinas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TempoPreparo")
                        .HasColumnType("int");

                    b.HasKey("ReceitaId");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("HealthWellbeing.Models.RestricaoAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gravidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RestricaoAlimentar");
                });

            modelBuilder.Entity("HealthWellbeing.Models.TipoExercicio", b =>
                {
                    b.Property<int>("TipoExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoExercicioId"));

                    b.Property<string>("CaracteristicasTipoExercicios")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DescricaoTipoExercicios")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NomeTipoExercicios")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoExercicioId");

                    b.ToTable("TipoExercicio");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainer");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("TrainingId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("HealthWellbeing.Models.TrainingType", b =>
                {
                    b.Property<int>("TrainingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrainingTypeId");

                    b.ToTable("TrainingType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.UtenteEvent", b =>
                {
                    b.Property<int>("UtenteEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtenteEventId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UtenteEventId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventId");

                    b.ToTable("UtenteEvent");
                });

            modelBuilder.Entity("ProblemaSaudeProfissionalExecutante", b =>
                {
                    b.Property<int>("ProblemasSaudeProblemaSaudeId")
                        .HasColumnType("int");

                    b.Property<int>("ProfissionalExecutanteId")
                        .HasColumnType("int");

                    b.HasKey("ProblemasSaudeProblemaSaudeId", "ProfissionalExecutanteId");

                    b.HasIndex("ProfissionalExecutanteId");

                    b.ToTable("ProblemaSaudeProfissionalExecutante");
                });

            modelBuilder.Entity("BeneficioTipoExercicio", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Beneficio", null)
                        .WithMany()
                        .HasForeignKey("BeneficiosBeneficioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.TipoExercicio", null)
                        .WithMany()
                        .HasForeignKey("TipoExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExercicioGenero", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Exercicio", null)
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Genero", null)
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExercicioGrupoMuscular", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Exercicio", null)
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.GrupoMuscular", null)
                        .WithMany()
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthWellbeing.Models.Activity", b =>
                {
                    b.HasOne("HealthWellbeing.Models.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergia", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alimento", "Alimento")
                        .WithMany("AlergiasRelacionadas")
                        .HasForeignKey("AlimentoId");

                    b.Navigation("Alimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alimento", b =>
                {
                    b.HasOne("HealthWellbeing.Models.CategoriaAlimento", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaAlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Badge", b =>
                {
                    b.HasOne("HealthWellbeing.Models.BadgeType", "BadgeType")
                        .WithMany("Badges")
                        .HasForeignKey("BadgeTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BadgeType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.BadgeRequirement", b =>
                {
                    b.HasOne("HealthWellbeing.Models.ActivityType", "ActivityTypes")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId");

                    b.HasOne("HealthWellbeing.Models.Badge", "Badge")
                        .WithMany("BadgeRequirements")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.EventType", "EventTypes")
                        .WithMany("BadgeRequirements")
                        .HasForeignKey("EventTypeId");

                    b.Navigation("ActivityTypes");

                    b.Navigation("Badge");

                    b.Navigation("EventTypes");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Customer", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Level", "Level")
                        .WithMany("Customer")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("HealthWellbeing.Models.CustomerBadge", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Badge", "Badge")
                        .WithMany("CustomerBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Customer", "Customer")
                        .WithMany("CustomerBadges")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Event", b =>
                {
                    b.HasOne("HealthWellbeing.Models.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId");

                    b.HasOne("HealthWellbeing.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.EventActivity", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Activity", null)
                        .WithMany("EventActivities")
                        .HasForeignKey("ActivityId1");

                    b.HasOne("HealthWellbeing.Models.Event", "Event")
                        .WithMany("EventActivities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Level", b =>
                {
                    b.HasOne("HealthWellbeing.Models.LevelCategory", "Category")
                        .WithMany("Levels")
                        .HasForeignKey("LevelCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Member", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithOne("Membership")
                        .HasForeignKey("HealthWellbeing.Models.Member", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Musculo", b =>
                {
                    b.HasOne("HealthWellbeing.Models.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Musculos")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Training", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.TrainingType", "TrainingType")
                        .WithMany()
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.UtenteEvent", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ProblemaSaudeProfissionalExecutante", b =>
                {
                    b.HasOne("HealthWellbeing.Models.ProblemaSaude", null)
                        .WithMany()
                        .HasForeignKey("ProblemasSaudeProblemaSaudeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.ProfissionalExecutante", null)
                        .WithMany()
                        .HasForeignKey("ProfissionalExecutanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthWellbeing.Models.Activity", b =>
                {
                    b.Navigation("EventActivities");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alimento", b =>
                {
                    b.Navigation("AlergiasRelacionadas");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Badge", b =>
                {
                    b.Navigation("BadgeRequirements");

                    b.Navigation("CustomerBadges");
                });

            modelBuilder.Entity("HealthWellbeing.Models.BadgeType", b =>
                {
                    b.Navigation("Badges");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Client", b =>
                {
                    b.Navigation("Membership");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Customer", b =>
                {
                    b.Navigation("CustomerBadges");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Event", b =>
                {
                    b.Navigation("EventActivities");
                });

            modelBuilder.Entity("HealthWellbeing.Models.EventType", b =>
                {
                    b.Navigation("BadgeRequirements");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("HealthWellbeing.Models.GrupoMuscular", b =>
                {
                    b.Navigation("Musculos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Level", b =>
                {
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HealthWellbeing.Models.LevelCategory", b =>
                {
                    b.Navigation("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
