// <auto-generated />
using System;
using HealthWellbeing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthWellbeing.Migrations
{
    [DbContext(typeof(HealthWellbeingDbContext))]
    partial class HealthWellbeingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeneficioTipoExercicio", b =>
                {
                    b.Property<int>("BeneficiosBeneficioId")
                        .HasColumnType("int");

                    b.Property<int>("TipoExercicioId")
                        .HasColumnType("int");

                    b.HasKey("BeneficiosBeneficioId", "TipoExercicioId");

                    b.HasIndex("TipoExercicioId");

                    b.ToTable("BeneficioTipoExercicio");
                });

            modelBuilder.Entity("ExercicioGenero", b =>
                {
                    b.Property<int>("ExercicioId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.HasKey("ExercicioId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("ExercicioGenero");
                });

            modelBuilder.Entity("ExercicioGrupoMuscular", b =>
                {
                    b.Property<int>("ExercicioId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("int");

                    b.HasKey("ExercicioId", "GrupoMuscularId");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("ExercicioGrupoMuscular");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Activity_", b =>
                {
                    b.Property<int>("Activity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Activity_Id"));

                    b.Property<string>("Activity_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberReps")
                        .HasColumnType("int");

                    b.Property<int?>("NumberSets")
                        .HasColumnType("int");

                    b.Property<decimal>("Weigth")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Activity_Id");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergia", b =>
                {
                    b.Property<int>("AlergiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlergiaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gravidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AlergiaId");

                    b.ToTable("Alergia");
                });

            modelBuilder.Entity("HealthWellbeing.Models.AlergiaAlimento", b =>
                {
                    b.Property<int>("AlergiaId")
                        .HasColumnType("int");

                    b.Property<int>("AlimentoId")
                        .HasColumnType("int");

                    b.HasKey("AlergiaId", "AlimentoId");

                    b.HasIndex("AlimentoId");

                    b.ToTable("AlergiaAlimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergy", b =>
                {
                    b.Property<int>("AlergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlergyId"));

                    b.Property<string>("AlergyName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("AlergyId");

                    b.ToTable("Alergy");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alimento", b =>
                {
                    b.Property<int>("AlimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlimentoId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaAlimentoId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GorduraGPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HidratosGPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KcalPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProteinaGPor100g")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AlimentoId");

                    b.HasIndex("CategoriaAlimentoId");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.AlimentoSubstituto", b =>
                {
                    b.Property<int>("AlimentoSubstitutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlimentoSubstitutoId"));

                    b.Property<int>("AlimentoOriginalId")
                        .HasColumnType("int");

                    b.Property<int>("AlimentoSubstitutoRefId")
                        .HasColumnType("int");

                    b.Property<double?>("FatorSimilaridade")
                        .HasColumnType("float");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProporcaoEquivalente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RestricaoAlimentarId")
                        .HasColumnType("int");

                    b.HasKey("AlimentoSubstitutoId");

                    b.HasIndex("AlimentoOriginalId");

                    b.HasIndex("AlimentoSubstitutoRefId");

                    b.HasIndex("RestricaoAlimentarId");

                    b.ToTable("AlimentoSubstitutos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Beneficio", b =>
                {
                    b.Property<int>("BeneficioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficioId"));

                    b.Property<string>("DescricaoBeneficio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeBeneficio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BeneficioId");

                    b.ToTable("Beneficio");
                });

            modelBuilder.Entity("HealthWellbeing.Models.CategoriaAlimento", b =>
                {
                    b.Property<int>("CategoriaAlimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaAlimentoId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaAlimentoId");

                    b.ToTable("CategoriaAlimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<double>("ActivityFactor")
                        .HasColumnType("float");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("CreateMember")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("HeightCm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ClientAlergy", b =>
                {
                    b.Property<int>("ClientAlergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientAlergyId"));

                    b.Property<int>("AlergyId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("ClientAlergyId");

                    b.HasIndex("AlergyId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientAlergy");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ComponenteReceita", b =>
                {
                    b.Property<int>("ComponenteReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComponenteReceitaId"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpcional")
                        .HasColumnType("bit");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeMedida")
                        .HasColumnType("int");

                    b.HasKey("ComponenteReceitaId");

                    b.HasIndex("AlimentoId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ComponenteReceita");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsulta"));

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataMarcacao")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdEspecialidade")
                        .HasColumnType("int");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.Property<string>("SearchTerm")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdEspecialidade");

                    b.HasIndex("IdMedico");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Doctor", b =>
                {
                    b.Property<int>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedico"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedico");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EventPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MinLevel")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("EventTypeId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("HealthWellbeing.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"));

                    b.Property<float>("EventTypeMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventTypeScoringMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Exercicio", b =>
                {
                    b.Property<int>("ExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExercicioId"));

                    b.Property<double>("CaloriasGastas")
                        .HasColumnType("float");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duracao")
                        .HasColumnType("float");

                    b.Property<string>("EquipamentoNecessario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExercicioNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instrucoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intencidade")
                        .HasColumnType("int");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("ExercicioId");

                    b.ToTable("Exercicio");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FoodId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("FoodCategory");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodHabitsPlan", b =>
                {
                    b.Property<int>("FoodHabitsPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodHabitsPlanId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FoodHabitsPlanId");

                    b.HasIndex("ClientId");

                    b.HasIndex("GoalId");

                    b.ToTable("FoodHabitsPlan");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodIntake", b =>
                {
                    b.Property<int>("FoodIntakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodIntakeId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("PortionId")
                        .HasColumnType("int");

                    b.Property<int>("PortionsEaten")
                        .HasColumnType("int");

                    b.Property<int>("PortionsPlanned")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FoodIntakeId");

                    b.HasIndex("FoodId");

                    b.HasIndex("PortionId");

                    b.HasIndex("PlanId", "Date", "FoodId")
                        .IsUnique();

                    b.ToTable("FoodIntake");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodNutritionalComponent", b =>
                {
                    b.Property<int>("FoodNutritionalComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodNutritionalComponentId"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("NutritionalComponentId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("FoodNutritionalComponentId");

                    b.HasIndex("NutritionalComponentId");

                    b.HasIndex("FoodId", "NutritionalComponentId")
                        .IsUnique();

                    b.ToTable("FoodNutritionalComponent");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodPlan", b =>
                {
                    b.Property<int>("PlanFoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanFoodId"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("PortionId")
                        .HasColumnType("int");

                    b.HasKey("PlanFoodId");

                    b.HasIndex("FoodId");

                    b.HasIndex("PlanId");

                    b.HasIndex("PortionId");

                    b.ToTable("FoodPlan");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodPlanDay", b =>
                {
                    b.Property<int>("FoodPlanDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodPlanDayId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("MealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("PortionId")
                        .HasColumnType("int");

                    b.Property<int>("PortionsPlanned")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FoodPlanDayId");

                    b.HasIndex("FoodId");

                    b.HasIndex("PortionId");

                    b.HasIndex("PlanId", "Date", "FoodId")
                        .IsUnique();

                    b.ToTable("FoodPlanDay");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"));

                    b.Property<string>("NomeGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GeneroId");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("int");

                    b.Property<int>("DailyFat")
                        .HasColumnType("int");

                    b.Property<int>("DailyHydrates")
                        .HasColumnType("int");

                    b.Property<int>("DailyProtein")
                        .HasColumnType("int");

                    b.Property<int>("DailyVitamins")
                        .HasColumnType("int");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GoalId");

                    b.HasIndex("ClientId");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("HealthWellbeing.Models.GrupoMuscular", b =>
                {
                    b.Property<int>("GrupoMuscularId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupoMuscularId"));

                    b.Property<string>("GrupoMuscularNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocalizacaoCorporal")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("GrupoMuscularId");

                    b.ToTable("GrupoMuscular");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelAtual")
                        .HasColumnType("int");

                    b.Property<string>("LevelCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelId");

                    b.ToTable("Level");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Member", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Musculo", b =>
                {
                    b.Property<int>("MusculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusculoId"));

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Musculo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MusculoId");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("Musculo");
                });

            modelBuilder.Entity("HealthWellbeing.Models.NutritionalComponent", b =>
                {
                    b.Property<int>("NutritionalComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionalComponentId"));

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NutritionalComponentId");

                    b.ToTable("NutritionalComponent");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Nutritionist", b =>
                {
                    b.Property<int>("NutritionistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionistId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("NutritionistId");

                    b.ToTable("Nutritionist");
                });

            modelBuilder.Entity("HealthWellbeing.Models.NutritionistClientPlan", b =>
                {
                    b.Property<int>("PlanClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanClientId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodHabitsPlanId")
                        .HasColumnType("int");

                    b.Property<int>("NutritionistId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("PlanClientId");

                    b.HasIndex("ClientId");

                    b.HasIndex("FoodHabitsPlanId");

                    b.HasIndex("NutritionistId");

                    b.ToTable("NutritionistClientPlan");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanId");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Portion", b =>
                {
                    b.Property<int>("PortionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortionId"));

                    b.Property<string>("PortionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortionId");

                    b.ToTable("Portion");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ProblemaSaude", b =>
                {
                    b.Property<int>("ProblemaSaudeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProblemaSaudeId"));

                    b.Property<int>("Gravidade")
                        .HasColumnType("int");

                    b.Property<string>("ProblemaCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProblemaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZonaAtingida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProblemaSaudeId");

                    b.ToTable("ProblemaSaude");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ProfissionalExecutante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProblemaSaudeId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProblemaSaudeId");

                    b.ToTable("ProfissionalExecutante");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Receita", b =>
                {
                    b.Property<int>("ReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceitaId"));

                    b.Property<decimal>("Calorias")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Gorduras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HidratosCarbono")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Porcoes")
                        .HasColumnType("int");

                    b.Property<decimal>("Proteinas")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("RestricoesAlimentarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempoPreparo")
                        .HasColumnType("int");

                    b.HasKey("ReceitaId");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("HealthWellbeing.Models.RestricaoAlimentar", b =>
                {
                    b.Property<int>("RestricaoAlimentarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestricaoAlimentarId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Gravidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("RestricaoAlimentarId");

                    b.ToTable("RestricaoAlimentar");
                });

            modelBuilder.Entity("HealthWellbeing.Models.RestricaoAlimentarAlimento", b =>
                {
                    b.Property<int>("RestricaoAlimentarId")
                        .HasColumnType("int");

                    b.Property<int>("AlimentoId")
                        .HasColumnType("int");

                    b.HasKey("RestricaoAlimentarId", "AlimentoId");

                    b.HasIndex("AlimentoId");

                    b.ToTable("RestricaoAlimentarAlimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Specialities", b =>
                {
                    b.Property<int>("IdEspecialidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidade"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdEspecialidade");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("HealthWellbeing.Models.TipoExercicio", b =>
                {
                    b.Property<int>("TipoExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoExercicioId"));

                    b.Property<string>("CaracteristicasTipoExercicios")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DescricaoTipoExercicios")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NomeTipoExercicios")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoExercicioId");

                    b.ToTable("TipoExercicio");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainer");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("TrainingId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("HealthWellbeing.Models.TrainingType", b =>
                {
                    b.Property<int>("TrainingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrainingTypeId");

                    b.ToTable("TrainingType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.UtenteSaude", b =>
                {
                    b.Property<int>("UtenteSaudeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtenteSaudeId"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Morada")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Niss")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nus")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UtenteSaudeId");

                    b.HasIndex("Nif")
                        .IsUnique();

                    b.HasIndex("Niss")
                        .IsUnique();

                    b.HasIndex("Nus")
                        .IsUnique();

                    b.ToTable("UtenteSaude");
                });

            modelBuilder.Entity("ReceitaRestricaoAlimentar", b =>
                {
                    b.Property<int>("ReceitasReceitaId")
                        .HasColumnType("int");

                    b.Property<int>("RestricoesAlimentaresRestricaoAlimentarId")
                        .HasColumnType("int");

                    b.HasKey("ReceitasReceitaId", "RestricoesAlimentaresRestricaoAlimentarId");

                    b.HasIndex("RestricoesAlimentaresRestricaoAlimentarId");

                    b.ToTable("ReceitaRestricaoAlimentar");
                });

            modelBuilder.Entity("BeneficioTipoExercicio", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Beneficio", null)
                        .WithMany()
                        .HasForeignKey("BeneficiosBeneficioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.TipoExercicio", null)
                        .WithMany()
                        .HasForeignKey("TipoExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExercicioGenero", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Exercicio", null)
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Genero", null)
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExercicioGrupoMuscular", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Exercicio", null)
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.GrupoMuscular", null)
                        .WithMany()
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthWellbeing.Models.AlergiaAlimento", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alergia", "Alergia")
                        .WithMany("AlimentosAssociados")
                        .HasForeignKey("AlergiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Alimento", "Alimento")
                        .WithMany("AlergiaRelacionadas")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alergia");

                    b.Navigation("Alimento");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alimento", b =>
                {
                    b.HasOne("HealthWellbeing.Models.CategoriaAlimento", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaAlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("HealthWellbeing.Models.AlimentoSubstituto", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alimento", "AlimentoOriginal")
                        .WithMany("Substitutos")
                        .HasForeignKey("AlimentoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Alimento", "AlimentoSubstitutoRef")
                        .WithMany("SubstituidoPor")
                        .HasForeignKey("AlimentoSubstitutoRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.RestricaoAlimentar", null)
                        .WithMany("Substitutos")
                        .HasForeignKey("RestricaoAlimentarId");

                    b.Navigation("AlimentoOriginal");

                    b.Navigation("AlimentoSubstitutoRef");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ClientAlergy", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alergy", "Alergy")
                        .WithMany("ClientAlergies")
                        .HasForeignKey("AlergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithMany("ClientAlergies")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alergy");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ComponenteReceita", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alimento", "Alimento")
                        .WithMany()
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Receita", "Receita")
                        .WithMany("Componentes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Consulta", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Specialities", "Speciality")
                        .WithMany("Consultas")
                        .HasForeignKey("IdEspecialidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Doctor", "Doctor")
                        .WithMany("Consultas")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Event", b =>
                {
                    b.HasOne("HealthWellbeing.Models.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Food", b =>
                {
                    b.HasOne("HealthWellbeing.Models.FoodCategory", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodHabitsPlan", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodIntake", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.FoodHabitsPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Portion", "Portion")
                        .WithMany()
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Plan");

                    b.Navigation("Portion");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodNutritionalComponent", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Food", "Food")
                        .WithMany("FoodNutritionalComponents")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.NutritionalComponent", "NutritionalComponent")
                        .WithMany("FoodNutritionalComponents")
                        .HasForeignKey("NutritionalComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("NutritionalComponent");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodPlan", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Food", "Food")
                        .WithMany("FoodPlans")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.FoodHabitsPlan", "Plan")
                        .WithMany("FoodPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Portion", "Portion")
                        .WithMany("FoodPlans")
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Plan");

                    b.Navigation("Portion");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodPlanDay", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.FoodHabitsPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.Portion", "Portion")
                        .WithMany()
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Plan");

                    b.Navigation("Portion");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Goal", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithMany("Goals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Member", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithOne("Membership")
                        .HasForeignKey("HealthWellbeing.Models.Member", "ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Musculo", b =>
                {
                    b.HasOne("HealthWellbeing.Models.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Musculos")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");
                });

            modelBuilder.Entity("HealthWellbeing.Models.NutritionistClientPlan", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Client", "Client")
                        .WithMany("NutritionistClientPlans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.FoodHabitsPlan", "FoodHabitsPlan")
                        .WithMany("NutritionistClientPlans")
                        .HasForeignKey("FoodHabitsPlanId");

                    b.HasOne("HealthWellbeing.Models.Nutritionist", "Nutritionist")
                        .WithMany("NutritionistClientPlans")
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("FoodHabitsPlan");

                    b.Navigation("Nutritionist");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ProfissionalExecutante", b =>
                {
                    b.HasOne("HealthWellbeing.Models.ProblemaSaude", null)
                        .WithMany("ProfissionalExecutante")
                        .HasForeignKey("ProblemaSaudeId");
                });

            modelBuilder.Entity("HealthWellbeing.Models.RestricaoAlimentarAlimento", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Alimento", "Alimento")
                        .WithMany("RestricoesAssociadas")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.RestricaoAlimentar", "RestricaoAlimentar")
                        .WithMany("AlimentosAssociados")
                        .HasForeignKey("RestricaoAlimentarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("RestricaoAlimentar");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Training", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.TrainingType", "TrainingType")
                        .WithMany()
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("ReceitaRestricaoAlimentar", b =>
                {
                    b.HasOne("HealthWellbeing.Models.Receita", null)
                        .WithMany()
                        .HasForeignKey("ReceitasReceitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthWellbeing.Models.RestricaoAlimentar", null)
                        .WithMany()
                        .HasForeignKey("RestricoesAlimentaresRestricaoAlimentarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergia", b =>
                {
                    b.Navigation("AlimentosAssociados");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alergy", b =>
                {
                    b.Navigation("ClientAlergies");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Alimento", b =>
                {
                    b.Navigation("AlergiaRelacionadas");

                    b.Navigation("RestricoesAssociadas");

                    b.Navigation("SubstituidoPor");

                    b.Navigation("Substitutos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Client", b =>
                {
                    b.Navigation("ClientAlergies");

                    b.Navigation("Goals");

                    b.Navigation("Membership");

                    b.Navigation("NutritionistClientPlans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Doctor", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Food", b =>
                {
                    b.Navigation("FoodNutritionalComponents");

                    b.Navigation("FoodPlans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("HealthWellbeing.Models.FoodHabitsPlan", b =>
                {
                    b.Navigation("FoodPlans");

                    b.Navigation("NutritionistClientPlans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.GrupoMuscular", b =>
                {
                    b.Navigation("Musculos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.NutritionalComponent", b =>
                {
                    b.Navigation("FoodNutritionalComponents");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Nutritionist", b =>
                {
                    b.Navigation("NutritionistClientPlans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Portion", b =>
                {
                    b.Navigation("FoodPlans");
                });

            modelBuilder.Entity("HealthWellbeing.Models.ProblemaSaude", b =>
                {
                    b.Navigation("ProfissionalExecutante");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Receita", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("HealthWellbeing.Models.RestricaoAlimentar", b =>
                {
                    b.Navigation("AlimentosAssociados");

                    b.Navigation("Substitutos");
                });

            modelBuilder.Entity("HealthWellbeing.Models.Specialities", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
